
[workspace]
members = ["./lib", "./gcode2svg", "gcode2obj", "bgcodeViewer"]
resolver = "2"
default-members = ["./lib"]

[workspace.package]
authors = ["martin <martinfrances107@hotmail.com>"]
edition = "2021"
repository = "https://github.com/martinfrances107/gcode2svg"
rust-version = "1.80"


[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[profile.dev]
debug = true
