
[workspace]
members = [
  "./lib",
  "./gcode2svg",
  "gcode2obj",
  "bgcodeViewer",
  "extract_thumbs",
]
resolver = "2"
default-members = ["./lib"]

[workspace.package]
authors = ["martin <martinfrances107@hotmail.com>"]
edition = "2021"
homepage = "https://github.com/martinfrances107/gcode2svg"
license = "MIT"
readme = "README.md"
repository = "https://github.com/martinfrances107/gcode2svg"
rust-version = "1.80"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[profile.dev]
debug = true
