[package]
authors = ["martin <martinfrances107@hotmail.com>"]
edition = "2021"
name = "bgcodeValidator"
categories = ["Parsing tools"]
description = "[Wavefront obj] Visualization tool for inspecting a g-code file. "
homepage = "https://github.com/martinfrances107/gcode2svg"
keywords = ["visualization"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/martinfrances107/gcode2svg"
rust-version = "1.80"
version = "0.1.0"

[[bin]]
name = "gcode2obj"
path = "src/main.rs"

[dependencies]
nom = "7.1.3"
gcode-nom = { path = "../lib" }
clap = { version = "4.5.20", features = ["derive"] }
