[package]
authors = ["martin <martinfrances107@hotmail.com>"]
edition = "2021"
name = "gcode2obj"
categories = ["Parsing tools"]
description = "[Wavefront obj] Visualization tool for inspecting a g-code file. "
homepage = "https://github.com/martinfrances107/gcode-nom"
keywords = ["visualization"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/martinfrances107/gcode-nom"
rust-version = "1.80"
version = "0.1.0"

[[bin]]
name = "gcode2obj"
path = "src/main.rs"

[dependencies]
gcode-nom = { version = "0.1.0", path = "../lib" }
clap = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
