use nom::branch::alt;
use nom::bytes::complete::tag;
use nom::character::complete::digit1;
use nom::combinator::map;
use nom::sequence::preceded;
use nom::IResult;

#[derive(Debug, Clone)]
pub(crate) enum Sentence<'a> {
    Comment,
    // linear move
    G1,
    // Home all axes
    G21,
    // use absolute coordinates.
    G90,
    // Drop - ie no further action.
    GDrop(&'a str),
    MDrop(&'a str),
}

impl<'a> Sentence<'a> {
    pub(crate) fn parse_line(line: &str) -> IResult<&str, Sentence> {
        // Most common first.
        alt((
            map(tag("G1"), |_| Sentence::G1),
            map(tag("G21"), |_| Sentence::G21),
            map(tag("G90"), |_| Sentence::G90),
            map(tag(";"), |_| Sentence::Comment),
            map(g_drop, Sentence::GDrop),
            map(m_drop, Sentence::MDrop),
        ))(line)
    }
}

// G commands that require no further action
fn g_drop(i: &str) -> IResult<&str, &str> {
    preceded(tag("G"), digit1)(i)
}

fn m_drop(i: &str) -> IResult<&str, &str> {
    preceded(tag("M"), digit1)(i)
}

#[cfg(test)]
mod test {

    static _INPUT: &str = r#"
; generated by Slic3r 1.2.9 on 2015-10-01 at 20:51:53

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.67mm
; infill extrusion width = 0.67mm
; solid infill extrusion width = 0.67mm
; top infill extrusion width = 0.67mm

M107
M190 S65 ; set bed temperature
M104 S205 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S205 ; wait for temperature to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
G1 E-1.00000 F1800.00000
G92 E0
G1 Z0.350 F7800.000
"#;

    #[test]
    fn parse_comment() {}
    #[test]
    fn parse_g1() {}
    #[test]
    fn parse_g_drop() {}
}
